# PRが作成または更新されたときに実行されるCIワークフロー
# Lintとテストを実行
name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      # Node.jsをセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Install dependencies
        run: |
          corepack enable
          yarn install --immutable

      - name: Lint
        run: |
          yarn typecheck
          yarn lint

      - name: Test
        run: yarn test
